{#
    This macro returns value 'Y' if the satellite is till in orbit
#}
{% macro get_geocode_unmatched(country_code) -%}
CASE
    WHEN country_code IS NOT NULL THEN country_code
    WHEN UPPER(cl.country) = 'ARAB SATELLITE COMMUNICATIONS ORGANIZATION' THEN 'SA'
    WHEN UPPER(cl.country) = 'IRAN' THEN 'IR'
    WHEN UPPER(cl.country) = 'EUROPEAN SPACE RESEARCH ORGANIZATION' THEN 'EU'
    WHEN UPPER(cl.country) = 'EUROPEAN ORGANIZATION FOR THE EXPLOITATION OF METEOROLOGICAL SATELLITES' THEN 'EU'
    WHEN UPPER(cl.country) = 'GLOBALSTAR' THEN 'US'
    WHEN UPPER(cl.country) = 'INTERNATIONAL SPACE STATION' THEN 'US'
    WHEN UPPER(cl.country) = 'TURKEY' THEN 'TR'
    WHEN UPPER(cl.country) = 'TAIWAN' THEN 'TW'
    WHEN UPPER(cl.country) = 'NORTH KOREA' THEN 'KP'
    WHEN UPPER(cl.country) = 'VIETNAM' THEN 'VN'
    WHEN UPPER(cl.country) = 'SOUTH KOREA' THEN 'KR'
    WHEN UPPER(cl.country) = 'ASIASAT CORP' THEN 'HK'
    WHEN UPPER(cl.country) = 'INTERNATIONAL MARITIME SATELLITE ORGANIZATION (INMARSAT)' THEN 'GB'
    WHEN UPPER(cl.country) = 'ABS GLOBAL LTD' THEN 'BM'
    WHEN UPPER(cl.country) = 'O3B NETWORKS' THEN 'LU'
    WHEN UPPER(cl.country) = 'REGIONAL AFRICAN SATELLITE COMMUNICATIONS ORG' THEN 'AE'
    WHEN UPPER(cl.country) = 'ORBITAL TELECOMMUNICATIONS SATELLITE (GLOBALSTAR)' THEN 'US'
    WHEN UPPER(cl.country) = 'NETHERLANDS' THEN 'NL'
    WHEN UPPER(cl.country) = 'NEW ICO' THEN NULL
    WHEN UPPER(cl.country) = 'SEA LAUNCH DEMO' THEN 'US'
    WHEN UPPER(cl.country) = 'EUROPEAN SPACE AGENCY' THEN 'EU'
    WHEN UPPER(cl.country) = 'EUROPEAN TELECOMMUNICATIONS SATELLITE ORGANIZATION (EUTELSAT)' THEN 'EU'
    WHEN UPPER(cl.country) = 'REPUBLIC OF THE UNION OF MYNAMAR' THEN 'MM'
    WHEN UPPER(cl.country) = 'VENEZUELA' THEN 'VE'
    WHEN UPPER(cl.country) = 'NORTH ATLANTIC TREATY ORGANIZATION' THEN 'BE'
    WHEN UPPER(cl.country) = 'UNITED KINGDOM' THEN 'GB'
    WHEN UPPER(cl.country) = 'INTERNATIONAL TELECOMMUNICATIONS SATELLITE ORGANIZATION (INTELSAT)' THEN 'US'
    WHEN UPPER(cl.country) = 'COMMONWEALTH OF INDEPENDENT STATES' THEN 'RU'
    WHEN UPPER(cl.country) = 'BOLIVIA' THEN 'BO'
    WHEN UPPER(cl.country) = 'LAOS' THEN 'LA'
    WHEN UPPER(cl.country) = 'SOCIÉTÉ EUROPÉENNE DES SATELLITES' THEN 'LU'
end
{%- endmacro %}
