# schema = {
#     'INTLDES':{'type': 'STRING', 'mode': 'REQUIRED'},
#     'NORAD_CAT_ID':{'type': 'INTEGER', 'mode': 'REQUIRED'},
#     'OBJECT_TYPE':{'type': 'STRING', 'mode': 'NULLABLE'},
#     'SATNAME':{'type': 'STRING', 'mode': 'NULLABLE'},
#     'COUNTRY':{'type': 'STRING', 'mode': 'NULLABLE'},
#     'LAUNCH':{'type': 'STRING', 'mode': 'NULLABLE'},
#     'SITE':{'type': 'STRING', 'mode': 'NULLABLE'},
#     'DECAY':{'type': 'STRING', 'mode': 'NULLABLE'},
#     'PERIOD':{'type': 'FLOAT', 'mode': 'NULLABLE'},
#     'INCLINATION':{'type': 'FLOAT', 'mode': 'NULLABLE'},
#     'APOGEE':{'type': 'FLOAT', 'mode': 'NULLABLE'},
#     'PERIGREE':{'type': 'FLOAT', 'mode': 'NULLABLE'},
#     'FILE':{'type': 'INTEGER', 'mode': 'NULLABLE'},
#     'LAUNCH_YEAR':{'type': 'INTEGER', 'mode': 'NULLABLE'},
#     'LAUNCH_NUM':{'type': 'INTEGER', 'mode': 'NULLABLE'},
#     'LAUCH_PIECE':{'type': 'STRING', 'mode': 'NULLABLE'},
#     'CURRENT':{'type': 'STRING', 'mode': 'NULLABLE'},
#     'OBJECT_NAME':{'type': 'STRING', 'mode': 'NULLABLE'},
#     'OBJECT_ID':{'type': 'STRING', 'mode': 'NULLABLE'},
#     'OBJECT_NUMBER':{'type': 'INTEGER', 'mode': 'NULLABLE'},
#     'unique_constraint': {
#         'fields': ['INTLDES', 'NORAD_CAT_ID'],
#         'description': 'UNIQUE constraint'
#     }
# }

schema = [
    {'name':'INTLDES', 'type': 'STRING', 'mode': 'REQUIRED'},
    {'name': 'NORAD_CAT_ID', 'type': 'INTEGER', 'mode': 'REQUIRED'},
    {'name': 'OBJECT_TYPE', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'SATNAME', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'COUNTRY', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'LAUNCH', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'SITE', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'DECAY', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'PERIOD', 'type': 'FLOAT', 'mode': 'NULLABLE'},
    {'name': 'INCLINATION', 'type': 'FLOAT', 'mode': 'NULLABLE'},
    {'name': 'APOGEE', 'type': 'FLOAT', 'mode': 'NULLABLE'},
    {'name': 'PERIGREE', 'type': 'FLOAT', 'mode': 'NULLABLE'},
    {'name': 'FILE', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'LAUNCH_YEAR', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'LAUNCH_NUM', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'LAUCH_PIECE', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'CURRENT', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'OBJECT_NAME', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'OBJECT_ID', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'OBJECT_NUMBER', 'type': 'INTEGER', 'mode': 'NULLABLE'},
]