version: 2

sources:
  - name: staging
    database: idyllic-aspect-382707
    schema: sat_data_all

    tables:
      - name: satcatdata

models:
  - name: stg_satcatdata
    columns:
      - name: sat_id
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn